# Generated by Django 6.0.3 on 2026-04-07 06:03

import django.contrib.gis.db.models.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('objectid', models.FloatField()),
                ('id', models.FloatField()),
                ('name', models.CharField(max_length=50)),
                ('division', models.CharField(max_length=50)),
                ('division_i', models.FloatField()),
                ('extent', models.CharField(blank=True, max_length=100, null=True)),
                ('shape_star', models.FloatField(blank=True, null=True)),
                ('shape_stle', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'district',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('division', models.CharField(max_length=50)),
                ('division_i', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'division',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Khasra',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('district', models.CharField(max_length=50)),
                ('dist_id', models.FloatField()),
                ('tehsil', models.CharField(max_length=50)),
                ('tehsil_id', models.FloatField()),
                ('qh', models.CharField(blank=True, max_length=254, null=True)),
                ('qh_id', models.FloatField(blank=True, null=True)),
                ('pc', models.CharField(blank=True, max_length=50, null=True)),
                ('pc_id', models.FloatField(blank=True, null=True)),
                ('mouza', models.CharField(max_length=50)),
                ('mouza_id', models.FloatField()),
                ('type', models.CharField(max_length=50)),
                ('m', models.IntegerField()),
                ('a', models.IntegerField()),
                ('k', models.IntegerField()),
                ('sk', models.CharField(blank=True, max_length=20, null=True)),
                ('khasra_id', models.FloatField()),
                ('label', models.CharField(max_length=25)),
                ('join_shp', models.CharField(blank=True, max_length=50, null=True)),
                ('karam', models.DecimalField(decimal_places=10, max_digits=20)),
                ('remarks', models.CharField(blank=True, max_length=50, null=True)),
                ('b', models.CharField(max_length=50)),
                ('mn', models.IntegerField()),
                ('division', models.CharField(max_length=50)),
                ('khewat_id', models.FloatField()),
                ('divn_id', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'khasra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mouza',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('district', models.CharField(max_length=100)),
                ('dist_id', models.FloatField()),
                ('tehsil', models.CharField(max_length=100)),
                ('tehsil_id', models.FloatField()),
                ('qh', models.CharField(blank=True, max_length=100, null=True)),
                ('qh_id', models.IntegerField(blank=True, null=True)),
                ('pc', models.CharField(blank=True, max_length=100, null=True)),
                ('pc_id', models.IntegerField(blank=True, null=True)),
                ('mouza', models.CharField(max_length=100)),
                ('mouza_id', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'mouza',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Murabba',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('district', models.CharField(max_length=50)),
                ('dist_id', models.FloatField()),
                ('tehsil', models.CharField(max_length=50)),
                ('tehsil_id', models.FloatField()),
                ('qh', models.CharField(blank=True, max_length=50, null=True)),
                ('qh_id', models.FloatField(blank=True, null=True)),
                ('pc', models.CharField(blank=True, max_length=50, null=True)),
                ('pc_id', models.FloatField(blank=True, null=True)),
                ('mouza', models.CharField(max_length=50)),
                ('mouza_id', models.FloatField()),
                ('murabba_no', models.IntegerField(db_column='m')),
                ('sheets', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'murabba',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RudaBoundary',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('oid', models.FloatField(db_column='oid')),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('folderpath', models.CharField(blank=True, max_length=254, null=True)),
                ('symbolid', models.FloatField(blank=True, null=True)),
                ('altmode', models.IntegerField(blank=True, null=True)),
                ('base', models.FloatField(blank=True, null=True)),
                ('clamped', models.IntegerField(blank=True, null=True)),
                ('extruded', models.IntegerField(blank=True, null=True)),
                ('snippet', models.TextField(blank=True, null=True)),
                ('popupinfo', models.CharField(blank=True, max_length=254, null=True)),
                ('shape_leng', models.FloatField(blank=True, null=True)),
                ('shape_area', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'ruda_boundary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tehsil',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('objectid', models.IntegerField()),
                ('id', models.FloatField()),
                ('name', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('district_i', models.IntegerField()),
                ('extent', models.CharField(blank=True, max_length=100, null=True)),
                ('shape_star', models.FloatField(blank=True, null=True)),
                ('shape_stle', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'tehsil',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trijunction',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('m1', models.CharField(blank=True, max_length=50, null=True)),
                ('m1_id', models.FloatField(blank=True, null=True)),
                ('m2', models.CharField(blank=True, max_length=50, null=True)),
                ('m2_id', models.FloatField(blank=True, null=True)),
                ('m3', models.CharField(blank=True, max_length=50, null=True)),
                ('m3_id', models.FloatField(blank=True, null=True)),
                ('layer', models.CharField(blank=True, max_length=254, null=True)),
                ('path', models.CharField(blank=True, max_length=254, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                'db_table': 'trijunction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin')], default='super_admin', max_length=20)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=400, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=200, null=True)),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
