# Generated by Django 6.0.3 on 2026-03-06 05:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Khasra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=50)),
                ('dist_id', models.FloatField()),
                ('tehsil', models.CharField(max_length=50)),
                ('tehsil_id', models.FloatField()),
                ('qh', models.CharField(blank=True, max_length=254, null=True)),
                ('qh_id', models.FloatField(blank=True, null=True)),
                ('pc', models.CharField(blank=True, max_length=50, null=True)),
                ('pc_id', models.FloatField(blank=True, null=True)),
                ('mouza', models.CharField(max_length=50)),
                ('mouza_id', models.FloatField()),
                ('type', models.CharField(max_length=50)),
                ('m', models.IntegerField()),
                ('a', models.IntegerField()),
                ('k', models.IntegerField()),
                ('sk', models.CharField(blank=True, max_length=20, null=True)),
                ('khasra_id', models.FloatField()),
                ('label', models.CharField(max_length=25)),
                ('join_shp', models.CharField(blank=True, max_length=50, null=True)),
                ('karam', models.DecimalField(decimal_places=10, max_digits=20)),
                ('remarks', models.CharField(blank=True, max_length=50, null=True)),
                ('b', models.CharField(max_length=50)),
                ('mn', models.IntegerField()),
                ('division', models.CharField(max_length=50)),
                ('khewat_id', models.FloatField()),
                ('divn_id', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'khasra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mouza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
                ('dist_id', models.IntegerField()),
                ('tehsil', models.CharField(max_length=100)),
                ('tehsil_id', models.IntegerField()),
                ('qh', models.CharField(blank=True, max_length=100, null=True)),
                ('qh_id', models.IntegerField(blank=True, null=True)),
                ('pc', models.CharField(blank=True, max_length=100, null=True)),
                ('pc_id', models.IntegerField(blank=True, null=True)),
                ('mouza', models.CharField(max_length=100)),
                ('mouza_id', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'mouza',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Murabba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=50)),
                ('dist_id', models.FloatField()),
                ('tehsil', models.CharField(max_length=50)),
                ('tehsil_id', models.FloatField()),
                ('qh', models.CharField(blank=True, max_length=50, null=True)),
                ('qh_id', models.FloatField(blank=True, null=True)),
                ('pc', models.CharField(blank=True, max_length=50, null=True)),
                ('pc_id', models.FloatField(blank=True, null=True)),
                ('mouza', models.CharField(max_length=50)),
                ('mouza_id', models.FloatField()),
                ('murabba_no', models.IntegerField(db_column='m')),
                ('sheets', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'murabba',
                'managed': False,
            },
        ),
    ]
