# Generated by Django 6.0.3 on 2026-03-10 07:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('objectid', models.FloatField()),
                ('id', models.FloatField()),
                ('name', models.CharField(max_length=50)),
                ('division', models.CharField(max_length=50)),
                ('division_i', models.FloatField()),
                ('extent', models.CharField(blank=True, max_length=100, null=True)),
                ('shape_star', models.FloatField(blank=True, null=True)),
                ('shape_stle', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'district',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('division', models.CharField(max_length=50)),
                ('division_i', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'division',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tehsil',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('objectid', models.FloatField()),
                ('id', models.FloatField()),
                ('name', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('district_i', models.FloatField()),
                ('extent', models.CharField(blank=True, max_length=100, null=True)),
                ('shape_star', models.FloatField(blank=True, null=True)),
                ('shape_stle', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'tehsil',
                'managed': False,
            },
        ),
    ]
