# Generated by Django 6.0.3 on 2026-06-12 12:27

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_division'),
    ]

    operations = [
        migrations.CreateModel(
            name='CBContour',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('layer', models.CharField(blank=True, max_length=255, null=True)),
                ('elevation', models.CharField(blank=True, max_length=50, null=True)),
                ('closed_con', models.CharField(blank=True, max_length=10, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('society_id', models.IntegerField(blank=True, null=True)),
                ('mauza_id', models.IntegerField(blank=True, null=True)),
                ('dist_id', models.IntegerField(blank=True, null=True)),
                ('tehsil_id', models.IntegerField(blank=True, null=True)),
                ('society', models.CharField(blank=True, max_length=100, null=True)),
                ('mauza', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('tehsil', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'cb_contour',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MasterPlan',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('descriptio', models.TextField(blank=True, null=True)),
                ('timestamp', models.CharField(blank=True, max_length=100, null=True)),
                ('begin', models.CharField(blank=True, max_length=100, null=True)),
                ('end', models.CharField(blank=True, max_length=100, null=True)),
                ('altitudemo', models.CharField(blank=True, max_length=50, null=True)),
                ('tessellate', models.CharField(blank=True, max_length=50, null=True)),
                ('extrude', models.CharField(blank=True, max_length=50, null=True)),
                ('visibility', models.CharField(blank=True, max_length=50, null=True)),
                ('draworder', models.CharField(blank=True, max_length=50, null=True)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('snippet', models.TextField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('society_id', models.IntegerField(blank=True, null=True)),
                ('mauza_id', models.IntegerField(blank=True, null=True)),
                ('dist_id', models.IntegerField(blank=True, null=True)),
                ('tehsil_id', models.IntegerField(blank=True, null=True)),
                ('society', models.CharField(blank=True, max_length=100, null=True)),
                ('mauza', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('tehsil', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'masterplan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Society',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('objectid', models.IntegerField()),
                ('society', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=100)),
                ('dist_id', models.IntegerField()),
                ('tehsil', models.CharField(max_length=100)),
                ('tehsil_id', models.IntegerField()),
                ('mauza', models.CharField(max_length=100)),
                ('mauza_id', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'society',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpotLevel',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.IntegerField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('society_id', models.IntegerField(blank=True, null=True)),
                ('mauza_id', models.IntegerField(blank=True, null=True)),
                ('dist_id', models.IntegerField(blank=True, null=True)),
                ('tehsil_id', models.IntegerField(blank=True, null=True)),
                ('society', models.CharField(blank=True, max_length=100, null=True)),
                ('mauza', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('tehsil', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'spot_level',
                'managed': False,
            },
        ),
    ]
