# Generated by Django 6.0.3 on 2026-03-30 08:38

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_district_division_tehsil'),
    ]

    operations = [
        migrations.CreateModel(
            name='RudaBoundary',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('oid', models.FloatField(db_column='oid_')),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('folderpath', models.CharField(blank=True, max_length=254, null=True)),
                ('symbolid', models.FloatField(blank=True, null=True)),
                ('altmode', models.IntegerField(blank=True, null=True)),
                ('base', models.FloatField(blank=True, null=True)),
                ('clamped', models.IntegerField(blank=True, null=True)),
                ('extruded', models.IntegerField(blank=True, null=True)),
                ('snippet', models.TextField(blank=True, null=True)),
                ('popupinfo', models.CharField(blank=True, max_length=254, null=True)),
                ('shape_leng', models.FloatField(blank=True, null=True)),
                ('shape_area', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'ruda_boundary',
                'managed': False,
            },
        ),
    ]
