# Generated by Django 6.0.3 on 2026-04-02 05:38

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rudaboundary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trijunction',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('m1', models.CharField(blank=True, max_length=50, null=True)),
                ('m1_id', models.FloatField(blank=True, null=True)),
                ('m2', models.CharField(blank=True, max_length=50, null=True)),
                ('m2_id', models.FloatField(blank=True, null=True)),
                ('m3', models.CharField(blank=True, max_length=50, null=True)),
                ('m3_id', models.FloatField(blank=True, null=True)),
                ('id', models.FloatField(blank=True, null=True)),
                ('layer', models.CharField(blank=True, max_length=254, null=True)),
                ('path', models.CharField(blank=True, max_length=254, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                'db_table': 'trijunction',
                'managed': False,
            },
        ),
    ]
