# Generated by Django 6.0.3 on 2026-06-12 12:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cbcontour_masterplan_society_spotlevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contour',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('layer', models.CharField(blank=True, max_length=255, null=True)),
                ('elevation', models.CharField(blank=True, max_length=50, null=True)),
                ('closed_con', models.CharField(blank=True, max_length=10, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('society_id', models.IntegerField(blank=True, null=True)),
                ('mauza_id', models.IntegerField(blank=True, null=True)),
                ('dist_id', models.IntegerField(blank=True, null=True)),
                ('tehsil_id', models.IntegerField(blank=True, null=True)),
                ('society', models.CharField(blank=True, max_length=100, null=True)),
                ('mauza', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('tehsil', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'contour',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='CBContour',
        ),
        migrations.AlterModelTable(
            name='spotlevel',
            table='spotlevel',
        ),
    ]
