# Generated by Django 6.0.3 on 2026-06-12 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_contour_delete_cbcontour_alter_spotlevel_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='spotlevel',
            table='spot_level',
        ),
    ]
