# Generated by Django 6.0.3 on 2026-06-13 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_spotlevel_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='society',
            options={'managed': True},
        ),
    ]
