# Generated by Django 6.0.3 on 2026-06-13 12:56

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_society_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RudaProposedRoads',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('kml_id', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('kml_desc', models.TextField(blank=True, null=True)),
                ('fid', models.IntegerField(blank=True, null=True)),
                ('entity', models.CharField(blank=True, max_length=100, null=True)),
                ('layer', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('linetype', models.CharField(blank=True, max_length=50, null=True)),
                ('elevation', models.FloatField(blank=True, null=True)),
                ('linewt', models.FloatField(blank=True, null=True)),
                ('refname', models.CharField(blank=True, max_length=255, null=True)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
            options={
                'db_table': 'ruda_proposed_roads',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='society',
            options={'managed': False},
        ),
    ]
