# Generated by Django 6.0.3 on 2026-06-15 07:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rudaproposedroads_alter_society_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acre',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('dist_id', models.FloatField(blank=True, null=True)),
                ('tehsil', models.CharField(blank=True, max_length=100, null=True)),
                ('tehsil_id', models.FloatField(blank=True, null=True)),
                ('mauza', models.CharField(blank=True, max_length=100, null=True)),
                ('mauza_id', models.FloatField(blank=True, null=True)),
                ('sq', models.FloatField(blank=True, null=True)),
                ('acre', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'acre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FieldPoints',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('layer', models.CharField(blank=True, max_length=50, null=True)),
                ('gm_type', models.CharField(blank=True, max_length=100, null=True)),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('elevation', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'db_table': 'fieldpoints',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Square',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('dist_id', models.FloatField(blank=True, null=True)),
                ('tehsil', models.CharField(blank=True, max_length=100, null=True)),
                ('tehsil_id', models.FloatField(blank=True, null=True)),
                ('kc', models.CharField(blank=True, max_length=100, null=True)),
                ('kc_id', models.FloatField(blank=True, null=True)),
                ('pc', models.CharField(blank=True, max_length=100, null=True)),
                ('pc_id', models.FloatField(blank=True, null=True)),
                ('mauza', models.CharField(blank=True, max_length=100, null=True)),
                ('mauza_id', models.FloatField(blank=True, null=True)),
                ('sq', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'square',
                'managed': False,
            },
        ),
    ]
