# Generated by Django 6.0.3 on 2026-06-15 08:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_acre_fieldpoints_square'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeodeticNetwork',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('easting_m', models.FloatField(blank=True, null=True)),
                ('northing_m', models.FloatField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('elevation', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'db_table': 'geodeticnetwork',
                'managed': False,
            },
        ),
    ]
