# Generated by Django 6.0.3 on 2026-06-15 19:55

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_geodeticnetwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('block', models.CharField(blank=True, max_length=100, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('project_id', models.IntegerField(blank=True, null=True)),
                ('project_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'blocks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BlockLevel',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('block', models.CharField(blank=True, max_length=255, null=True)),
                ('dimension', models.CharField(blank=True, max_length=255, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'block_level',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CameraLocation',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('sr_no', models.IntegerField(blank=True, null=True)),
                ('project', models.CharField(blank=True, max_length=255, null=True)),
                ('camera', models.CharField(blank=True, max_length=255, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('x', models.FloatField(blank=True, null=True)),
                ('coordinate', models.CharField(blank=True, max_length=255, null=True)),
                ('iframe_lin', models.TextField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'cameralocation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('plot_nu', models.CharField(blank=True, max_length=100, null=True)),
                ('plot_area', models.CharField(blank=True, max_length=100, null=True)),
                ('block', models.CharField(blank=True, max_length=255, null=True)),
                ('shape_leng', models.FloatField(blank=True, null=True)),
                ('shape_area', models.FloatField(blank=True, null=True)),
                ('dimension', models.CharField(blank=True, max_length=255, null=True)),
                ('parkfront', models.CharField(blank=True, max_length=50, null=True)),
                ('rd_ft', models.CharField(blank=True, max_length=50, null=True)),
                ('storey', models.CharField(blank=True, max_length=50, null=True)),
                ('rd_facing', models.CharField(blank=True, max_length=50, null=True)),
                ('h', models.IntegerField(blank=True, null=True)),
                ('demar', models.CharField(blank=True, max_length=255, null=True)),
                ('possession', models.CharField(blank=True, max_length=255, null=True)),
                ('poss_st', models.CharField(blank=True, max_length=255, null=True)),
                ('canceled', models.CharField(blank=True, max_length=50, null=True)),
                ('site_plan', models.CharField(blank=True, max_length=255, null=True)),
                ('unique_id', models.IntegerField(blank=True, null=True)),
                ('tr_srno', models.IntegerField(blank=True, null=True)),
                ('tr_own', models.TextField(blank=True, null=True)),
                ('tr_p_no', models.CharField(blank=True, max_length=255, null=True)),
                ('tr_cate', models.CharField(blank=True, max_length=255, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'plots',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('brief_name', models.CharField(blank=True, max_length=100, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'projects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('block', models.CharField(blank=True, max_length=255, null=True)),
                ('width', models.CharField(blank=True, max_length=100, null=True)),
                ('road_type', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'road',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SWPoint',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'swpoint',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WSL',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('shape_leng', models.FloatField(blank=True, null=True)),
                ('dia', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'wsl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WSPoint',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'wspoint',
                'managed': False,
            },
        ),
    ]
