# Generated by Django 6.0.3 on 2026-06-15 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_block_blocklevel_cameralocation_plot_project_road_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='block',
            table='block',
        ),
        migrations.AlterModelTable(
            name='plot',
            table='plot',
        ),
        migrations.AlterModelTable(
            name='project',
            table='project',
        ),
    ]
