# Generated by Django 6.0.3 on 2026-06-17 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_block_table_alter_plot_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMauza',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mauza', models.ForeignKey(db_column='mauza_id', on_delete=django.db.models.deletion.CASCADE, related_name='mauza_projects', to='api.mauza')),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='project_mauzas', to='api.project')),
            ],
            options={
                'db_table': 'project_mauza',
                'managed': True,
                'unique_together': {('project', 'mauza')},
            },
        ),
    ]
