# Generated by Django 6.0.3 on 2026-06-17 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_projectmauza'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectmauza',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='projectmauza',
            name='khasra',
            field=models.ForeignKey(blank=True, db_column='khasra_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='khasra_mauzas', to='api.khasra'),
        ),
        migrations.AddField(
            model_name='projectmauza',
            name='murabba',
            field=models.ForeignKey(blank=True, db_column='murabba_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='murabba_mauzas', to='api.murabba'),
        ),
        migrations.AlterUniqueTogether(
            name='projectmauza',
            unique_together={('project', 'mauza', 'khasra', 'murabba')},
        ),
    ]
