# Generated by Django 6.0.3 on 2026-06-20 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_projectmauza_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='trijunction',
            table='trijuntion',
        ),
    ]
