# Generated by Django 6.0.3 on 2026-06-20 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_trijunction_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='trijunction',
            table='trijunction',
        ),
    ]
