# Generated by Django 6.0.3 on 2026-06-22 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_sync_projectmauza_square_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Murabba',
        ),
    ]
