# Generated by Django 6.0.3 on 2026-07-03 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_delete_murabba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmauza',
            name='khasra',
            field=models.ForeignKey(blank=True, db_column='khasra_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_mauzas', to='api.khasra'),
        ),
        migrations.AlterField(
            model_name='projectmauza',
            name='mauza',
            field=models.ForeignKey(blank=True, db_column='mauza_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_mauzas', to='api.mauza', to_field='mauza_id'),
        ),
    ]
