# Generated by Django 6.0.3 on 2026-07-10 08:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_projectmauza_khasra_alter_projectmauza_mauza'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityLevelService',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('layer', models.CharField(blank=True, max_length=26, null=True)),
                ('gm_type', models.CharField(blank=True, max_length=17, null=True)),
                ('elevation', models.SmallIntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('area_225ac', models.FloatField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=254, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'city_level_service',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CityLevelServicePoints',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('layer', models.CharField(blank=True, max_length=26, null=True)),
                ('gm_type', models.CharField(blank=True, max_length=21, null=True)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('area_225ac', models.FloatField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=254, null=True)),
                ('orig_fid', models.FloatField(blank=True, null=True)),
                ('elevation', models.SmallIntegerField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'city_level_service_points',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExistingForest',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('lu_type', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('area_sqfee', models.FloatField(blank=True, null=True)),
                ('area_acre', models.FloatField(blank=True, null=True)),
                ('area_225ac', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'existing_forest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ForestBoundary',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('objectid_1', models.FloatField(blank=True, null=True)),
                ('objectid', models.FloatField(blank=True, null=True)),
                ('f_zone', models.CharField(blank=True, max_length=100, null=True)),
                ('f_circle', models.CharField(blank=True, max_length=100, null=True)),
                ('f_div', models.CharField(blank=True, max_length=100, null=True)),
                ('f_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gps_area', models.FloatField(blank=True, null=True)),
                ('gross_area', models.FloatField(blank=True, null=True)),
                ('f_type', models.CharField(blank=True, max_length=100, null=True)),
                ('legal_stat', models.CharField(blank=True, max_length=50, null=True)),
                ('shape_leng', models.FloatField(blank=True, null=True)),
                ('shape_area', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'forest_boundary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MpPrincipleZoning',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('area225a', models.FloatField(blank=True, null=True)),
                ('zoning_cat', models.CharField(blank=True, max_length=255, null=True)),
                ('area_sqft', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'mp_principle_zoning',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrecientBoundary',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('area_acre', models.FloatField(blank=True, null=True)),
                ('phases', models.CharField(blank=True, max_length=100, null=True)),
                ('phases_new', models.CharField(blank=True, max_length=100, null=True)),
                ('shape_leng', models.FloatField(blank=True, null=True)),
                ('shape_area', models.FloatField(blank=True, null=True)),
                ('area_sqft', models.FloatField(blank=True, null=True)),
                ('area_225ac', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'precient_boundary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProposedRoadNetwork',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('gm_layer', models.CharField(blank=True, max_length=32, null=True)),
                ('gm_type', models.CharField(blank=True, max_length=17, null=True)),
                ('elevation', models.SmallIntegerField(blank=True, null=True)),
                ('layer', models.CharField(blank=True, max_length=254, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'proposed_road_network',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='River',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('layer', models.CharField(blank=True, max_length=17, null=True)),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('area_sqft', models.FloatField(blank=True, null=True)),
                ('area_225ac', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'river',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RiverRavi',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('type', models.CharField(blank=True, max_length=254, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'river_ravi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RudaJurisdiction',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('objectid', models.FloatField(blank=True, null=True)),
                ('area_usacr', models.FloatField(blank=True, null=True)),
                ('phases', models.CharField(blank=True, max_length=50, null=True)),
                ('districts', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('tehsils', models.CharField(blank=True, max_length=100, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'ruda_jurisdiction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RudaPlanningBoundary',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('area_usacr', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('area_sqft', models.FloatField(blank=True, null=True)),
                ('area_225ac', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'ruda_planning_boundary',
                'managed': False,
            },
        ),
    ]
