# Generated by Django 6.0.3 on 2026-07-10 16:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_citylevelservice_citylevelservicepoints_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardedLand',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('district', models.CharField(blank=True, max_length=254, null=True)),
                ('tehsil', models.CharField(blank=True, max_length=254, null=True)),
                ('mouza', models.CharField(blank=True, max_length=254, null=True)),
                ('square', models.FloatField(blank=True, null=True)),
                ('khasra', models.FloatField(blank=True, null=True)),
                ('sub_khasra', models.FloatField(blank=True, null=True)),
                ('khasra_lab', models.CharField(blank=True, max_length=254, null=True)),
                ('agri_river', models.CharField(blank=True, max_length=254, null=True)),
                ('land_type', models.CharField(blank=True, max_length=254, null=True)),
                ('remarks', models.CharField(blank=True, max_length=254, null=True)),
                ('area_sqft', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, db_column='date', null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'awardedland',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PossessionLand',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('district', models.CharField(blank=True, max_length=254, null=True)),
                ('tehsil', models.CharField(blank=True, max_length=254, null=True)),
                ('mouza', models.CharField(blank=True, max_length=254, null=True)),
                ('square', models.FloatField(blank=True, null=True)),
                ('khasra', models.FloatField(blank=True, null=True)),
                ('khasra_lab', models.CharField(blank=True, max_length=254, null=True)),
                ('award_zone', models.CharField(blank=True, max_length=254, null=True)),
                ('projects', models.CharField(blank=True, max_length=254, null=True)),
                ('l_type', models.CharField(blank=True, max_length=254, null=True)),
                ('land_owner', models.CharField(blank=True, max_length=254, null=True)),
                ('lp_name', models.CharField(blank=True, max_length=254, null=True)),
                ('remarks', models.CharField(blank=True, max_length=254, null=True)),
                ('date', models.CharField(blank=True, db_column='date', max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'possessionland',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RtwAlignment',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('package', models.CharField(blank=True, max_length=254, null=True)),
                ('length', models.CharField(blank=True, max_length=254, null=True)),
                ('area_sqft', models.FloatField(blank=True, null=True)),
                ('area_ac225', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, db_column='date', null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'rtwalignment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RtwPackage',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('layer', models.CharField(blank=True, max_length=254, null=True)),
                ('map_name', models.CharField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('package', models.CharField(blank=True, max_length=254, null=True)),
                ('area_acres', models.FloatField(blank=True, null=True)),
                ('closed', models.CharField(blank=True, max_length=50, null=True)),
                ('label_pos', models.CharField(blank=True, max_length=254, null=True)),
                ('ruda_phase', models.CharField(blank=True, max_length=254, null=True)),
                ('area_sqkm', models.FloatField(blank=True, null=True)),
                ('aaa', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'rtwpackage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StateLand',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('district', models.CharField(blank=True, max_length=254, null=True)),
                ('tehsil', models.CharField(blank=True, max_length=254, null=True)),
                ('mouza', models.CharField(blank=True, max_length=254, null=True)),
                ('square', models.SmallIntegerField(blank=True, null=True)),
                ('khasra', models.SmallIntegerField(blank=True, null=True)),
                ('sub_khasra', models.SmallIntegerField(blank=True, null=True)),
                ('khasra_lab', models.CharField(blank=True, max_length=254, null=True)),
                ('remarks', models.CharField(blank=True, max_length=35, null=True)),
                ('state_land', models.CharField(blank=True, max_length=254, null=True)),
                ('area_sqft', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, db_column='date', null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'stateland',
                'managed': False,
            },
        ),
    ]
