# Generated by Django 6.0.3 on 2026-07-13 07:30

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_awardedland_possessionland_rtwalignment_rtwpackage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbdulHakeemMotorwayM3',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('objectid', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('layer', models.CharField(blank=True, max_length=17, null=True)),
                ('kml_style', models.CharField(blank=True, max_length=15, null=True)),
                ('tessellate', models.IntegerField(blank=True, null=True)),
                ('name_1', models.CharField(blank=True, max_length=254, null=True)),
                ('name_2', models.CharField(blank=True, max_length=254, null=True)),
                ('shape_leng', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'abdulhakeemmotorwaym3',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HardoSohalMuslimRoad',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('objectid', models.FloatField(blank=True, null=True)),
                ('row', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('length_km', models.CharField(blank=True, max_length=254, null=True)),
                ('remarks', models.CharField(blank=True, max_length=254, null=True)),
                ('kacha_pacc', models.CharField(blank=True, max_length=254, null=True)),
                ('shape_leng', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'hardosohalmuslimroad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JinnahAvenueRoad',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('objectid', models.FloatField(blank=True, null=True)),
                ('row', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('length_km', models.CharField(blank=True, max_length=254, null=True)),
                ('remarks', models.CharField(blank=True, max_length=254, null=True)),
                ('kacha_pacc', models.CharField(blank=True, max_length=254, null=True)),
                ('shape_leng', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'jinnahavenueroad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KalaKhataJiInterchange',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('objectid', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=12, null=True)),
                ('layer', models.CharField(blank=True, max_length=17, null=True)),
                ('kml_style', models.CharField(blank=True, max_length=15, null=True)),
                ('tessellate', models.FloatField(blank=True, null=True)),
                ('shape_leng', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'kalakhatajiinterchange',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KatarBundRoad',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('oid', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('folderpath', models.CharField(blank=True, max_length=254, null=True)),
                ('symbolid', models.FloatField(blank=True, null=True)),
                ('altmode', models.IntegerField(blank=True, null=True)),
                ('base', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True)),
                ('clamped', models.IntegerField(blank=True, null=True)),
                ('extruded', models.IntegerField(blank=True, null=True)),
                ('snippet', models.CharField(blank=True, max_length=254, null=True)),
                ('popupinfo', models.CharField(blank=True, max_length=254, null=True)),
                ('shape_leng', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True)),
                ('row', models.CharField(blank=True, max_length=254, null=True)),
                ('buffer', models.CharField(blank=True, max_length=254, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'katarbundroad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LahoreBypass',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('oid', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('folderpath', models.CharField(blank=True, max_length=254, null=True)),
                ('symbolid', models.FloatField(blank=True, null=True)),
                ('altmode', models.IntegerField(blank=True, null=True)),
                ('base', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True)),
                ('clamped', models.IntegerField(blank=True, null=True)),
                ('extruded', models.IntegerField(blank=True, null=True)),
                ('snippet', models.CharField(blank=True, max_length=254, null=True)),
                ('popupinfo', models.CharField(blank=True, max_length=254, null=True)),
                ('shape_leng', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True)),
                ('row', models.CharField(blank=True, max_length=254, null=True)),
                ('buffer', models.CharField(blank=True, max_length=254, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'lahorebypass',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SialkotMotorway',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('objectid_1', models.FloatField(blank=True, null=True)),
                ('objectid', models.FloatField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=150, null=True)),
                ('length_km', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True)),
                ('shape_leng', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'sialkotmotorway',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransportationRoads',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('objectid_1', models.FloatField(blank=True, null=True)),
                ('objectid', models.FloatField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=22, null=True)),
                ('name', models.CharField(blank=True, max_length=63, null=True)),
                ('shape_leng', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True)),
                ('shape_le_1', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'transportationroads',
                'managed': False,
            },
        ),
    ]
