# Generated by Django 6.0.3 on 2026-07-13 06:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_branchcanal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributary',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('objectid_1', models.IntegerField(blank=True, null=True)),
                ('objectid', models.IntegerField(blank=True, null=True)),
                ('imis_code', models.CharField(blank=True, max_length=50, null=True)),
                ('division', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_ch', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('zone', models.CharField(blank=True, db_column='zone_', max_length=255, null=True)),
                ('circle', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('canal_type', models.CharField(blank=True, db_column='type_', max_length=50, null=True)),
                ('gca', models.CharField(blank=True, max_length=100, null=True)),
                ('cca', models.CharField(blank=True, max_length=100, null=True)),
                ('designed_d', models.FloatField(blank=True, null=True)),
                ('tail_rd', models.FloatField(blank=True, null=True)),
                ('a_tail_g', models.FloatField(blank=True, null=True)),
                ('a_tail_d', models.FloatField(blank=True, null=True)),
                ('flow_type', models.CharField(blank=True, db_column='flow_type_', max_length=255, null=True)),
                ('shape_leng', models.FloatField(blank=True, null=True)),
                ('shape_le_1', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'distributary',
                'managed': False,
            },
        ),
    ]
