# Generated by Django 6.0.3 on 2026-07-13 08:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_branchcanal_distributary_existingdrains_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LahoreRingRoad',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('objectid_1', models.IntegerField(blank=True, null=True)),
                ('objectid', models.IntegerField(blank=True, null=True)),
                ('fid', models.IntegerField(blank=True, db_column='fid_', null=True)),
                ('entity_name', models.CharField(blank=True, db_column='entity', max_length=255, null=True)),
                ('layer', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.IntegerField(blank=True, null=True)),
                ('linetype', models.CharField(blank=True, max_length=255, null=True)),
                ('elevation', models.FloatField(blank=True, null=True)),
                ('linewt', models.IntegerField(blank=True, null=True)),
                ('refname', models.CharField(blank=True, max_length=255, null=True)),
                ('orig_fid', models.IntegerField(blank=True, null=True)),
                ('shape_leng', models.FloatField(blank=True, null=True)),
                ('shape_le_1', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'lahoreringroad',
                'managed': False,
            },
        ),
    ]
