# Generated by Django 6.0.3 on 2026-07-13 08:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_lahoreringroad'),
    ]

    operations = [
        migrations.CreateModel(
            name='KalaKhataiInterchange',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('objectid', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=12, null=True)),
                ('layer', models.CharField(blank=True, max_length=17, null=True)),
                ('kml_style', models.CharField(blank=True, max_length=15, null=True)),
                ('tessellate', models.FloatField(blank=True, null=True)),
                ('shape_leng', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'kalakhataiinterchange',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='KalaKhataJiInterchange',
        ),
    ]
