# Generated by Django 6.0.3 on 2026-07-13 08:52

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_kalakhataiinterchange_delete_kalakhatajiinterchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='JinnahAvenue',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('objectid', models.FloatField(blank=True, null=True)),
                ('row', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('length_km', models.CharField(blank=True, max_length=254, null=True)),
                ('remarks', models.CharField(blank=True, max_length=254, null=True)),
                ('kacha_pacc', models.CharField(blank=True, max_length=254, null=True)),
                ('shape_leng', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'jinnahavenue',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='JinnahAvenueRoad',
        ),
    ]
