# Generated by Django 6.0.3 on 2026-07-13 09:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_jinnahavenue_delete_jinnahavenueroad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bridges',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('osm_id', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('ref', models.CharField(blank=True, max_length=255, null=True)),
                ('bridge_type', models.CharField(blank=True, db_column='type', max_length=255, null=True)),
                ('oneway', models.IntegerField(blank=True, null=True)),
                ('bridge', models.IntegerField(blank=True, null=True)),
                ('maxspeed', models.IntegerField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'bridges',
                'managed': False,
            },
        ),
    ]
