# Generated by Django 6.0.3 on 2026-07-13 09:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_bridges'),
    ]

    operations = [
        migrations.CreateModel(
            name='GanjaKalanTruckStand',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('objectid', models.IntegerField(blank=True, null=True)),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('tehsil', models.CharField(blank=True, max_length=255, null=True)),
                ('mouza', models.CharField(blank=True, max_length=255, null=True)),
                ('square', models.IntegerField(blank=True, null=True)),
                ('khasra', models.IntegerField(blank=True, null=True)),
                ('sub_khasra', models.IntegerField(blank=True, null=True)),
                ('khasra_lab', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('area_sqft', models.FloatField(blank=True, null=True)),
                ('shape_leng', models.FloatField(blank=True, null=True)),
                ('shape_area', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'ganjakalantruckstand',
                'managed': False,
            },
        ),
    ]
