# Generated by Django 6.0.3 on 2026-07-13 09:52

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_ganjakalantruckstand'),
    ]

    operations = [
        migrations.CreateModel(
            name='LahoreRapidMassTransit',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('shape_leng', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'lahorerapidmasstransit',
                'managed': False,
            },
        ),
    ]
