# Generated by Django 6.0.3 on 2026-07-13 07:34

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_proposedwwtp'),
    ]

    operations = [
        migrations.CreateModel(
            name='SWTPSite',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('sq_ft', models.FloatField(blank=True, null=True)),
                ('marla', models.FloatField(blank=True, null=True)),
                ('kanal', models.FloatField(blank=True, null=True)),
                ('acres', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'swtp_site',
                'managed': False,
            },
        ),
    ]
