# Generated by Django 6.0.3 on 2026-07-13 07:39

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_swtpsite'),
    ]

    operations = [
        migrations.CreateModel(
            name='WWTPSites',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('objectid', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('site_type', models.CharField(blank=True, db_column='type', max_length=100, null=True)),
                ('shape_leng', models.FloatField(blank=True, null=True)),
                ('shape_area', models.FloatField(blank=True, null=True)),
                ('created_us', models.CharField(blank=True, max_length=255, null=True)),
                ('created_da', models.CharField(blank=True, max_length=255, null=True)),
                ('last_edite', models.CharField(blank=True, max_length=255, null=True)),
                ('last_edi_1', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'wwtp_sites',
                'managed': False,
            },
        ),
    ]
