# Generated by Django 6.0.3 on 2026-07-13 09:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_lahorerapidmasstransit'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrangeTrack',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('folderpath', models.CharField(blank=True, max_length=500, null=True)),
                ('symbolid', models.IntegerField(blank=True, null=True)),
                ('altmode', models.IntegerField(blank=True, null=True)),
                ('base', models.FloatField(blank=True, null=True)),
                ('clamped', models.IntegerField(blank=True, null=True)),
                ('extruded', models.IntegerField(blank=True, null=True)),
                ('snippet', models.TextField(blank=True, null=True)),
                ('popupinfo', models.TextField(blank=True, null=True)),
                ('shape_leng', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'orangetrack',
                'managed': False,
            },
        ),
    ]
