# Generated by Django 6.0.3 on 2026-07-13 10:08

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_orangetrack'),
    ]

    operations = [
        migrations.CreateModel(
            name='RailwayLine',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('objectid_1', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('shape_leng', models.FloatField(blank=True, null=True)),
                ('shape_le_1', models.FloatField(blank=True, null=True)),
                ('shape_le_2', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'railwayline',
                'managed': False,
            },
        ),
    ]
