# Generated by Django 6.0.3 on 2026-07-15 11:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_hudiaradrain'),
    ]

    operations = [
        migrations.CreateModel(
            name='RudaKhasra',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('district_text', models.CharField(blank=True, db_column='district', max_length=100, null=True)),
                ('tehsil_text', models.CharField(blank=True, db_column='tehsil', max_length=100, null=True)),
                ('mauza_text', models.CharField(blank=True, db_column='mauza', max_length=100, null=True)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('area_sqft', models.FloatField(blank=True, null=True)),
                ('shape_leng', models.FloatField(blank=True, null=True)),
                ('shape_area', models.FloatField(blank=True, null=True)),
                ('kc', models.CharField(blank=True, max_length=254, null=True)),
                ('kc_id', models.FloatField(blank=True, null=True)),
                ('pc', models.CharField(blank=True, max_length=100, null=True)),
                ('pc_id', models.FloatField(blank=True, null=True)),
                ('hadbust_no', models.IntegerField(blank=True, null=True)),
                ('asse_cir', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('karam', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('sq', models.IntegerField(blank=True, null=True)),
                ('kh', models.IntegerField(blank=True, null=True)),
                ('sk', models.CharField(blank=True, max_length=20, null=True)),
                ('join_shp', models.CharField(blank=True, max_length=50, null=True)),
                ('khasra_id', models.FloatField(blank=True, null=True)),
                ('khewat_id', models.FloatField(blank=True, null=True)),
                ('khatoni_no', models.FloatField(blank=True, null=True)),
                ('dc_rate', models.FloatField(blank=True, null=True)),
                ('b', models.CharField(blank=True, max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'ruda_khasra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RudaMauza',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('district_text', models.CharField(blank=True, db_column='district', max_length=100, null=True)),
                ('tehsil_text', models.CharField(blank=True, db_column='tehsil', max_length=100, null=True)),
                ('kc', models.CharField(blank=True, max_length=100, null=True)),
                ('kc_id', models.IntegerField(blank=True, null=True)),
                ('pc', models.CharField(blank=True, max_length=100, null=True)),
                ('mauza', models.CharField(max_length=100)),
                ('mauza_id', models.FloatField(blank=True, null=True, unique=True)),
                ('notified_b', models.CharField(blank=True, max_length=100, null=True)),
                ('proposed_b', models.CharField(blank=True, max_length=100, null=True)),
                ('new_ext', models.CharField(blank=True, max_length=100, null=True)),
                ('prepared_b', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'ruda_mauza',
                'managed': False,
            },
        ),
    ]
