# Generated by Django 6.0.3 on 2026-07-16 10:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_rudakhasra_rudamauza'),
    ]

    operations = [
        migrations.CreateModel(
            name='LahoreTransportationRoad',
            fields=[
                ('gid', models.AutoField(db_column='gid', primary_key=True, serialize=False)),
                ('oid', models.CharField(blank=True, db_column='__oid', max_length=100, null=True)),
                ('name', models.CharField(blank=True, db_column='name', max_length=255, null=True)),
                ('shape_leng', models.FloatField(blank=True, db_column='shape_leng', null=True)),
                ('type', models.CharField(blank=True, db_column='type', max_length=100, null=True)),
                ('popupinfo', models.TextField(blank=True, db_column='popupinfo', null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, db_column='geom', null=True, srid=4326)),
            ],
            options={
                'db_table': 'lahore_transportation_roads',
                'managed': False,
            },
        ),
    ]
