# Generated by Django 6.0.3 on 2026-07-17 10:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_lahoretransportationroad'),
    ]

    operations = [
        migrations.CreateModel(
            name='RudaSquare',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('district', models.CharField(db_index=True, max_length=100)),
                ('tehsil', models.CharField(db_index=True, max_length=100)),
                ('mouza', models.CharField(db_index=True, max_length=150)),
                ('square', models.IntegerField(db_index=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'ruda_square',
                'managed': False,
            },
        ),
    ]
