# Generated by Django 6.0.3 on 2026-07-22 06:38

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_rudasquare'),
    ]

    operations = [
        migrations.CreateModel(
            name='RudaNotifiedPhasesBoundary',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('area_acre', models.FloatField(blank=True, null=True)),
                ('phases', models.CharField(blank=True, max_length=15, null=True)),
                ('phases_new', models.CharField(blank=True, max_length=50, null=True)),
                ('shape_leng', models.FloatField(blank=True, null=True)),
                ('shape_le_1', models.FloatField(blank=True, null=True)),
                ('shape_area', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'ruda_notified_phases_boundary',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AbdulHakeemMotorwayM3',
        ),
        migrations.DeleteModel(
            name='BranchCanal',
        ),
        migrations.DeleteModel(
            name='Bridges',
        ),
        migrations.DeleteModel(
            name='Distributary',
        ),
        migrations.DeleteModel(
            name='ExistingDrains',
        ),
        migrations.DeleteModel(
            name='GanjaKalanTruckStand',
        ),
        migrations.DeleteModel(
            name='HardoSohalMuslimRoad',
        ),
        migrations.DeleteModel(
            name='HudiaraDrain',
        ),
        migrations.DeleteModel(
            name='IrrigationNetwork',
        ),
        migrations.DeleteModel(
            name='JinnahAvenue',
        ),
        migrations.DeleteModel(
            name='KalaKhataiInterchange',
        ),
        migrations.DeleteModel(
            name='KatarBandWWTP',
        ),
        migrations.DeleteModel(
            name='KatarBundRoad',
        ),
        migrations.DeleteModel(
            name='LahoreBypass',
        ),
        migrations.DeleteModel(
            name='LahoreRapidMassTransit',
        ),
        migrations.DeleteModel(
            name='LahoreRingRoad',
        ),
        migrations.DeleteModel(
            name='LinkCanal',
        ),
        migrations.DeleteModel(
            name='OrangeTrack',
        ),
        migrations.DeleteModel(
            name='ProposedWWTP',
        ),
        migrations.DeleteModel(
            name='RailwayLine',
        ),
        migrations.DeleteModel(
            name='RailwayStations',
        ),
        migrations.DeleteModel(
            name='SialkotMotorway',
        ),
        migrations.DeleteModel(
            name='TransportationRoads',
        ),
        migrations.AlterModelTable(
            name='swtpsite',
            table='swtp_sites',
        ),
    ]
