# Generated by Django 6.0.3 on 2026-07-28 13:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_rudanotifiedphasesboundary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposedRoads',
            fields=[
                ('gid', models.AutoField(db_column='gid', primary_key=True, serialize=False)),
                ('id', models.IntegerField(blank=True, db_column='id', db_index=True, null=True)),
                ('road_type', models.CharField(blank=True, db_column='road_type', db_index=True, max_length=50, null=True)),
                ('row', models.FloatField(blank=True, db_column='row', null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, db_column='geom', null=True, srid=4326)),
            ],
            options={
                'db_table': 'ruda_proposed_road',
                'managed': False,
            },
        ),
    ]
