# Generated by Django 6.0.3 on 2026-07-28 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_proposedroads'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='proposedroads',
            table='proposed_road',
        ),
    ]
