# Generated by Django 6.0.3 on 2026-07-29 10:53

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_proposedroads_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='PPPScheme',
            fields=[
                ('gid', models.AutoField(db_column='gid', primary_key=True, serialize=False)),
                ('scheme_nam', models.CharField(blank=True, db_column='scheme_nam', max_length=255, null=True)),
                ('area_225a', models.FloatField(blank=True, db_column='area_225a', null=True)),
                ('ruda_st', models.CharField(blank=True, db_column='ruda_st', max_length=255, null=True)),
                ('area', models.FloatField(blank=True, db_column='area', null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, db_column='geom', null=True, srid=4326)),
            ],
            options={
                'db_table': 'phs_ppp_schemes',
                'managed': False,
            },
        ),
    ]
