# Generated by Django 6.0.3 on 2026-07-29 11:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_phspppscheme_delete_pppscheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExistingDrain',
            fields=[
                ('gid', models.AutoField(db_column='gid', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='name', max_length=255, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, db_column='geom', null=True, srid=4326)),
            ],
            options={
                'db_table': 'existing_drains',
                'managed': False,
            },
        ),
    ]
