# Generated by Django 6.0.3 on 2026-07-30 07:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_existingdrain'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposedRoad',
            fields=[
                ('gid', models.AutoField(db_column='gid', primary_key=True, serialize=False)),
                ('road_type', models.CharField(blank=True, db_column='road_type', max_length=255, null=True)),
                ('row', models.FloatField(blank=True, db_column='row', null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, db_column='geom', null=True, srid=4326)),
            ],
            options={
                'db_table': 'proposed_road',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ProposedRoads',
        ),
    ]
