# Generated by Django 6.0.3 on 2026-09-10 06:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_proposedroad_delete_proposedroads'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloodExtent',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'floodextent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SWLine',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('objectid', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('dia', models.CharField(blank=True, max_length=50, null=True)),
                ('shape_leng', models.FloatField(blank=True, null=True)),
                ('project_id', models.IntegerField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
            options={
                'db_table': 'sw_line',
                'managed': False,
            },
        ),
    ]
