# Generated by Django 6.0.3 on 2026-09-15 08:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_floodextent_swline'),
    ]

    operations = [
        migrations.CreateModel(
            name='KmzPrintLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=32, unique=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='kmz_prints/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('project', models.CharField(blank=True, default='', max_length=255)),
                ('project_type', models.CharField(blank=True, default='', max_length=255)),
                ('phase', models.CharField(blank=True, default='', max_length=255)),
                ('feature_count', models.PositiveIntegerField(default=0)),
                ('geometry_types', models.JSONField(blank=True, default=list)),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('printed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('printed_by', models.CharField(blank=True, default='', max_length=255)),
                ('print_title', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'kmz_print_log',
                'ordering': ('-printed_at',),
            },
        ),
    ]
