# Generated by Django 6.0.3 on 2026-09-15 09:19

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_kmzprintlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='kmzprintlog',
            name='folder_name',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='kmzprintlog',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to=api.models.kmz_print_upload_path),
        ),
        migrations.AlterField(
            model_name='kmzprintlog',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=api.models.kmz_print_upload_path),
        ),
    ]
