# Generated by Django 6.0.4 on 2026-06-09 07:33

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('hospital', 'Hospital'), ('school', 'School'), ('park', 'Park'), ('mosque', 'Mosque'), ('transport', 'Transport')], max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('source', models.CharField(default='osm', max_length=50)),
                ('source_id', models.CharField(max_length=150, unique=True)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['category'], name='amenities_a_categor_6e9c72_idx'), django.contrib.postgres.indexes.GistIndex(fields=['geom'], name='amenities_a_geom_18e747_gist')],
            },
        ),
    ]
