from .CreateJinnahAvenueRoadView import CreateJinnahAvenueRoadView
from .UpdateJinnahAvenueRoadView import UpdateJinnahAvenueRoadView
from .DeleteJinnahAvenueRoadView import DeleteJinnahAvenueRoadView
from .ListJinnahAvenueRoadView import ListJinnahAvenueRoadView
