from ...common_imports import *
from rest_framework.decorators import action
from django.http import HttpResponse
import io
import json
import re
import zipfile
from django.utils import timezone

from .camera_snapshot import CameraSnapshotError, capture_camera_snapshot


def _safe_filename(value, fallback="camera"):
    value = str(value or fallback).strip()
    value = re.sub(r"[^A-Za-z0-9._-]+", "_", value).strip("_")
    return value or fallback


class ListCameraLocationView(viewsets.ViewSet):
    queryset = CameraLocation.objects.all()
    serializer_class = CameraLocationSerializer
    permission_classes = [AllowAny]

    def list(self, request, *args, **kwargs):
        try:
            gid = request.query_params.get("gid")
            project = request.query_params.get("project")
            project_id = request.query_params.get("project_id")
            camera = request.query_params.get("camera")

            queryset = CameraLocation.objects.select_related("project_fk")

            if gid:
                obj = queryset.filter(gid=gid).first()

                if not obj:
                    return ApiResponse(
                        status=status.HTTP_404_NOT_FOUND,
                        message="CameraLocation not found.",
                        http_status=status.HTTP_404_NOT_FOUND,
                    ).create_response()

                return ApiResponse(
                    status=status.HTTP_200_OK,
                    message="CameraLocation found.",
                    data=CameraLocationSerializer(obj).data,
                    http_status=status.HTTP_200_OK,
                ).create_response()

            if project:
                queryset = queryset.filter(project__icontains=project)

            if project_id:
                queryset = queryset.filter(project_fk_id=project_id)

            if camera:
                queryset = queryset.filter(camera__icontains=camera)

            serializer = CameraLocationSerializer(queryset, many=True)

            return ApiResponse(
                status=status.HTTP_200_OK,
                message="CameraLocation list fetched successfully.",
                data=serializer.data,
                http_status=status.HTTP_200_OK,
            ).create_response()

        except Exception as e:
            return ApiResponse(
                status=status.HTTP_500_INTERNAL_SERVER_ERROR,
                message="Server error.",
                data=str(e),
                http_status=status.HTTP_500_INTERNAL_SERVER_ERROR,
            ).create_response()

    @action(detail=True, methods=["get"], url_path="snapshot")
    def snapshot(self, request, pk=None):
        """Download the current camera view as a JPEG.

        Route generated by DRF:
            GET /camera-location/<gid>/snapshot/
        """
        camera = CameraLocation.objects.filter(gid=pk).first()
        if not camera:
            return Response(
                {"detail": "Camera not found."},
                status=status.HTTP_404_NOT_FOUND,
            )

        if not camera.iframe_lin:
            return Response(
                {"detail": "This camera has no iframe URL configured."},
                status=status.HTTP_422_UNPROCESSABLE_ENTITY,
            )

        try:
            result = capture_camera_snapshot(camera.iframe_lin)
        except CameraSnapshotError as exc:
            return Response(
                {
                    "detail": str(exc),
                    "camera_id": camera.gid,
                    "camera": camera.camera,
                },
                status=status.HTTP_502_BAD_GATEWAY,
            )

        filename = f"{_safe_filename(camera.camera, 'camera')}_{camera.gid}.jpeg"
        response = HttpResponse(result.jpeg_bytes, content_type="image/jpeg")
        response["Content-Disposition"] = f'attachment; filename="{filename}"'
        response["Cache-Control"] = "no-store"
        response["X-Camera-Id"] = str(camera.gid)
        response["X-Camera-Snapshot-Source"] = result.source
        return response

    @action(detail=False, methods=["post"], url_path="download-snapshots")
    def download_snapshots(self, request):
        """Download snapshots for cameras in a project as one ZIP archive.

        Body:
            {"project_id": 17, "camera_ids": [1, 2, 3]}

        camera_ids is optional. If omitted, all cameras for project_id are used.
        """
        project_id = request.data.get("project_id")
        camera_ids = request.data.get("camera_ids") or []

        queryset = CameraLocation.objects.select_related("project_fk")

        if project_id:
            queryset = queryset.filter(project_fk_id=project_id)
        elif not camera_ids:
            return Response(
                {"detail": "project_id or camera_ids is required."},
                status=status.HTTP_400_BAD_REQUEST,
            )

        if camera_ids:
            queryset = queryset.filter(gid__in=camera_ids)

        cameras = list(queryset.order_by("gid"))
        if not cameras:
            return Response(
                {"detail": "No cameras were found for this request."},
                status=status.HTTP_404_NOT_FOUND,
            )

        archive_buffer = io.BytesIO()
        errors = []
        successes = 0

        with zipfile.ZipFile(archive_buffer, "w", compression=zipfile.ZIP_DEFLATED) as archive:
            for camera in cameras:
                if not camera.iframe_lin:
                    errors.append(
                        {
                            "camera_id": camera.gid,
                            "camera": camera.camera,
                            "error": "No iframe URL configured.",
                        }
                    )
                    continue

                try:
                    result = capture_camera_snapshot(camera.iframe_lin)
                    filename = f"{_safe_filename(camera.camera, 'camera')}_{camera.gid}.jpeg"
                    archive.writestr(filename, result.jpeg_bytes)
                    successes += 1
                except CameraSnapshotError as exc:
                    errors.append(
                        {
                            "camera_id": camera.gid,
                            "camera": camera.camera,
                            "error": str(exc),
                        }
                    )

            manifest = {
                "project_id": project_id,
                "requested_camera_ids": camera_ids,
                "generated_at": timezone.now().isoformat(),
                "success_count": successes,
                "error_count": len(errors),
                "errors": errors,
            }
            archive.writestr("_capture_manifest.json", json.dumps(manifest, indent=2))

        if successes == 0:
            return Response(
                {
                    "detail": "No camera images could be captured.",
                    "errors": errors,
                },
                status=status.HTTP_502_BAD_GATEWAY,
            )

        archive_buffer.seek(0)
        project_label = _safe_filename(
            cameras[0].project_fk.name if cameras[0].project_fk else cameras[0].project,
            f"project_{project_id or 'cameras'}",
        )
        date_stamp = timezone.localdate().isoformat()
        filename = f"{project_label}_camera_images_{date_stamp}.zip"

        response = HttpResponse(archive_buffer.getvalue(), content_type="application/zip")
        response["Content-Disposition"] = f'attachment; filename="{filename}"'
        response["Cache-Control"] = "no-store"
        return response
