from .CreateSialkotMotorwayView import CreateSialkotMotorwayView
from .UpdateSialkotMotorwayView import UpdateSialkotMotorwayView
from .DeleteSialkotMotorwayView import DeleteSialkotMotorwayView
from .ListSialkotMotorwayView import ListSialkotMotorwayView
