from .CreatePossessionLandView import CreatePossessionLandView
from .DeletePossessionLandView import DeletePossessionLandView
from .ListPossessionLandView import ListPossessionLandView
from .UpdatePossessionLandView import UpdatePossessionLandView
