from .Division import *
from .District import *
from .Tehsils import *
from .Mouza import *
from .Murabba import *
from .Khasra import *
from .Trijunction import *
from .RudaBoundary import *
from .UserView import *