export const projectDatasetConfigs = {
  projectBoundary: {
    title: "Project Boundary",
    description: "Project boundaries within the RUDA cadastral system.",
    type: "projectBoundary",
    endpoint: "/project/",
    columns: [
      { key: "name", label: "Project" },
      { key: "type", label: "Type" },
      { key: "phase", label: "Phase" },
    ],
  },
  blockBoundary: {
    title: "Block Boundary",
    description: "Block boundaries within selected RUDA projects.",
    type: "blockBoundary",
    endpoint: "/block/",
    columns: [
      { key: "name", label: "Name" },
      { key: "block", label: "Block" },
      { key: "area", label: "Area" },
      { key: "project", label: "Project ID" },
    ],
  },
  masterplanPlotData: {
    title: "Masterplan Plot Data",
    description: "Masterplan plot boundaries and related project data.",
    type: "masterplanPlotData",
    endpoint: "/plot/",
    columns: [
      { key: "plot_no", label: "Plot No" },
      { key: "name", label: "Name" },
      { key: "type", label: "Type" },
      { key: "plot_area", label: "Plot Area" },
      { key: "project", label: "Project ID" },
      { key: "block", label: "Block ID" },
    ],
  },
  spotLevel: {
    title: "Spot Level",
    description: "Survey spot-level points and elevation information.",
    type: "spotLevel",
    endpoint: "/spot-level/",
    columns: [
      { key: "id", label: "ID" },
      { key: "x", label: "X" },
      { key: "y", label: "Y" },
      { key: "z", label: "Z" },
      { key: "elevation", label: "Elevation" },
      { key: "project", label: "Project ID" },
    ],
  },
  waterSupplyPoints: {
    title: "Water Supply Points",
    description: "Water supply nodes, assets and service points.",
    type: "waterSupplyPoints",
    endpoint: "/wspoint-features-cb1/",
    columns: [
      { key: "name", label: "Name" },
      { key: "type", label: "Type" },
      { key: "project_id", label: "Project ID" },
    ],
  },
  waterSupplyLines: {
    title: "Water Supply Lines",
    description: "Water supply network and distribution line datasets.",
    type: "waterSupplyLines",
    endpoint: "/wsl-cb1/",
    columns: [
      { key: "name", label: "Name" },
      { key: "type", label: "Type" },
      { key: "dia", label: "Diameter" },
      { key: "shape_leng", label: "Length" },
      { key: "project_id", label: "Project ID" },
    ],
  },
  sewerPoints: {
    title: "Sewer Points",
    description: "Sewer network nodes, chambers and control points.",
    type: "sewerPoints",
    endpoint: "/swpoint-cb1/",
    columns: [
      { key: "name", label: "Name" },
      { key: "type", label: "Type" },
      { key: "project_id", label: "Project ID" },
    ],
  },
  sewerLines: {
    title: "Sewer Lines",
    description: "Sewerage network and pipeline alignment datasets.",
    type: "sewerLines",
    endpoint: "/sw-line/",
    columns: [
      { key: "name", label: "Name" },
      { key: "dia", label: "Diameter" },
      { key: "shape_leng", label: "Length" },
      { key: "project_id", label: "Project ID" },
    ],
  },
};
